//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WaveSoapFront.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_WAV_FILTER                  102
#define IDD_PROPPAGE_DECLICK            104
#define IDD_PROPPAGE_NOISEREDUCT        106
#define IDR_MAINFRAME                   128
#define IDR_WAVESOTYPE                  129
#define IDR_MENU_TIME_RULER             130
#define IDR_MP3TYPE                     130
#define IDD_SELECTION_DIALOG            131
#define IDR_WMATYPE                     131
#define IDR_POPUP_SCALED_SCROLL_VIEW    132
#define IDR_ALLTYPES                    132
#define IDD_DIALOG_MORE_NOISEREDUCTION  133
#define IDR_MENU_AMPLITUDE_RULER        133
#define IDD_DIALOG_MORE_DECLICK         134
#define IDR_MENU_FFT_RULER              134
#define IDD_DIALOGBAR_MDI_CHILD         135
#define IDD_DIALOG_OPEN_TEMPLATE        136
#define IDR_MENU_POPUP_SAMPLE_RATE      137
#define IDR_MENU_POPUP_CHANNELS         138
#define IDD_DIALOG_COPY_CHANNELS_SELECT 138
#define IDR_MENU_POPUP_SAMPLE_SIZE      139
#define IDD_DIALOG_PASTE_MODE_SELECT    139
#define IDR_MENU_WAVE_VIEW              140
#define IDD_DIALOG_VOLUME_CHANGE        140
#define IDR_MENU_WAVE_VIEW_SELECTION    141
#define IDD_DIALOG_VOLUME_CHANGE_MONO   141
#define IDR_MENU_FFT_VIEW               142
#define IDD_DIALOG_GOTO                 142
#define IDR_MENU_CURRENT_POSITION       143
#define IDD_DIALOG_DC_OFFSET            143
#define IDR_MENU_SELECTION_LENGTH       144
#define IDD_DIALOG_STATISTICS           144
#define IDR_MENU_FILE_LENGTH            145
#define IDD_DIALOG_NORMALIZE            145
#define IDD_DIALOG_RESAMPLE             146
#define IDD_DIALOG_STATISTICS_MONO      147
#define IDD_DIALOG_OPEN_TEMPLATE1       148
#define IDD_DIALOG_SAVE_TEMPLATE        149
#define IDC_CURSOR_BEAM                 150
#define IDC_CURSOR_BEAM_LEFT            151
#define IDC_CURSOR_BEAM_RIGHT           152
#define IDC_EDIT_MIN_CLICK_AMPLITUDE    1000
#define IDC_TAB_SWITCH_VIEW_MODE        1000
#define IDC_CHECK_LOG_CLICKS            1001
#define IDC_EDIT_CLICK_LOG_FILENAME     1002
#define IDC_COMBO_SELECTION             1002
#define IDC_CLICK_LOG_BROWSE_BUTTON     1003
#define IDC_EDIT_START                  1003
#define IDC_CHECK_LOG_CLICKS_ONLY       1004
#define IDC_EDIT_END                    1004
#define IDC_EDIT_CLICK_TO_NOISE         1005
#define IDC_EDIT3                       1005
#define IDC_EDIT_LENGTH                 1005
#define IDC_EDIT_MAX_CLICK_LENGTH       1006
#define IDC_EDIT_ATTACK_RATE            1007
#define IDC_SPIN1                       1007
#define IDC_SPIN_START                  1007
#define IDC_EDIT_DECAY_RATE             1008
#define IDC_SPIN2                       1008
#define IDC_SPIN_END                    1008
#define IDC_EDIT_CLICK_IMPORT_FILENAME  1009
#define IDC_SPIN3                       1009
#define IDC_SPIN_LENGTH                 1009
#define IDC_CLICK_IMPORT_BROWSE_BUTTON  1010
#define IDC_COMBO2                      1010
#define IDC_COMBO_FORMAT                1010
#define IDC_CHECK_IMPORT_CLICKS         1011
#define IDC_CHECK_NOISE_REDUCTION       1011
#define IDC_CHECK_READONLY              1011
#define IDC_COMBO_ATTRIBUTES            1011
#define IDC_CHECK_DIRECT                1012
#define IDC_COMBO1                      1013
#define IDC_COMBO_RECENT                1013
#define IDC_COMBODB_PERCENT             1013
#define IDC_COMBO_TIME_FORMAT           1013
#define IDC_STATIC_FILE_TYPE            1016
#define IDC_STATIC_FILE_FORMAT          1017
#define IDC_EDIT_LOWER_FREQUENCY        1018
#define IDC_STATIC_ATTRIBUTES           1019
#define IDC_EDIT_TRANSIENT_THRESHOLD    1020
#define IDC_EDIT_NOISE_CRITERION        1021
#define IDC_EDIT_FILE_COMMENTS          1021
#define IDC_EDIT_TONE_PREFERENCE        1022
#define IDC_EDIT_NOISE_AREA_THRESHOLD_HIGH 1023
#define IDC_STATIC_FILE_LENGTH          1023
#define IDC_COMBO_FFT_ORDER             1024
#define IDC_RADIO_LEFT                  1024
#define IDC_EDIT_NOISE_REDUCTION        1025
#define IDC_RADIO_RIGHT                 1025
#define IDC_EDIT_NOISE_AREA_THRESHOLD_LOW 1026
#define IDC_RADIO_CHANNEL_BOTH          1026
#define IDC_BUTTON_MORE                 1027
#define IDC_RADIO_SELECT                1027
#define IDC_SLIDER_VOLUME_LEFT          1028
#define IDC_BUTTON_RESET_DEFAULT        1029
#define IDC_EDIT_VOLUME_LEFT            1029
#define IDC_BUTTON_REVERT_INITIAL       1030
#define IDC_BUTTON_SELECTION            1030
#define IDC_SLIDER_TEMPO                1030
#define IDC_BUTTON_MORE_SETTINGS        1031
#define IDC_STATIC_SELECTION            1031
#define IDC_EDIT_TEMPO                  1031
#define IDC_EDIT_AGGRESSIVNESS          1032
#define IDC_CHECK_UNDO                  1032
#define IDC_EDIT_NEAR_MASKING_COEFF     1033
#define IDC_SLIDER_VOLUME_RIGHT         1033
#define IDC_EDIT_NEAR_MASKING_DISTANCE_HIGH 1034
#define IDC_CHECK_DEHUMMING             1034
#define IDC_EDIT_FAR_MASKING_COEFF      1035
#define IDC_CHECK_DECLICKING            1035
#define IDC_EDIT_VOLUME_RIGHT           1035
#define IDC_EDIT4                       1036
#define IDC_CHECKLOCK_CHANNELS          1036
#define IDC_EDIT_NEAR_MASKING_DISTANCE_LOW 1037
#define IDC_TAB_VIEW_SWITCH             1037
#define IDC_STATIC_RIGHT_CHANNEL        1037
#define IDC_EDIT_MASKING_TIME_HIGH      1038
#define IDC_STATIC_LEFT_CHANNEL         1038
#define IDC_EDIT_MASKING_TIME_LOW       1039
#define IDC_BUTTON_PLAY                 1039
#define IDC_RADIO_CHANNEL               1040
#define IDC_RADIO2                      1041
#define IDC_RADIO3                      1042
#define IDC_RADIO_DC_SELECT             1043
#define IDC_EDIT_DC_OFFSET              1044
#define IDC_CHECK_5SECONDS              1045
#define IDC_EDIT_LEFT                   1046
#define IDC_EDIT_RIGHT                  1047
#define IDC_CHECK_LOCK_CHANNELS         1047
#define IDC_SLIDER_LEVEL                1048
#define IDC_EDIT_LEVEL                  1049
#define IDC_RADIO_CHANGE_RATE           1050
#define IDC_RADIO_CHANGE_PITCH          1051
#define IDC_CHECK_CHANGE_RATE_ONLY      1052
#define IDC_SLIDER_RATE                 1053
#define IDC_EDIT_RATE                   1054
#define IDC_CHECK_COMPATIBLE_FORMATS    1055
#define IDC_VIEW_RULER_SAMPLES          32771
#define IDC_VIEW_RULER_HHMMSS           32772
#define IDC_VIEW_RULER_SECONDS          32773
#define IDC_SOUND_PLAY                  32774
#define IDC_SOUND_PAUSE                 32775
#define IDC_SOUND_STOP                  32776
#define IDC_VIEW_SHOW_FFT               32777
#define IDC_VIEW_WAVEFORM               32778
#define IDC_PROCESS_DO_ULF              32780
#define IDC_PROCESS_DO_DECLICKING       32781
#define IDC_PROCESS_NOISE_REDUCTION     32782
#define ID_EDIT_DELETE                  32783
#define ID_EDIT_STOP                    32784
#define ID_FILE_SAVE_ALL                32786
#define ID_EDIT_PASTE_NEW               32787
#define ID_EDIT_GOTO                    32788
#define IDC_VIEW_AMPL_RULER_SAMPLES     32789
#define ID_VIEW_ZOOMIN                  32790
#define ID_VIEW_ZOOMOUT                 32791
#define IDC_VIEW_AMPL_RULER_DECIBELS    32792
#define ID_VIEW_ZOOM_OUT2               32793
#define ID_VIEW_ZOOMIN2                 32794
#define ID_VIEW_ZOOMINHOR               32795
#define IDS_BAD_FLOAT_VALUE             32796
#define IDS_VALUE_REQUIRED              32797
#define IDS_VALUE_TOO_LOW               32798
#define IDS_VALUE_TOO_HIGH              32799
#define IDS_INI_FILTER                  32800
#define ID_VIEW_ZOOM_OUT3               32801
#define ID_VIEW_ZOOMIN3                 32802
#define ID_VIEW_ZOOMINHOR2              32803
#define ID_INDICATOR_MOUSE_POSITION     32804
#define ID_VIEW_ZOOMINVERT              32810
#define ID_VIEW_ZOOMOUTHOR              32811
#define ID_VIEW_ZOOMOUTVERT             32812
#define ID_VIEW_ZOOMINVERT2             32813
#define ID_VIEW_ZOOMOUTHOR2             32814
#define ID_VIEW_ZOOMOUTVERT2            32815
#define IDS_STRING_UNABLE_TO_CREATE_CLIPBOARD 32816
#define IDS_STRING_OPERATION_IN_PROGRESS 32817
#define IDS_STRING_UNABLE_TO_OPEN_AUDIO_DEVICE 32818
#define IDS_STRING_UNABLE_TO_ALLOCATE_AUDIO_BUFFERS 32819
#define IDS_UNABLE_TO_LOAD_WAVEFORMAT   32820
#define IDS_UNABLE_TO_FIND_DATA_CHUNK   32821
#define IDS_UNABLE_TO_OPEN_WAVE_FILE    32822
#define IDS_FILE_OPEN_ACCESS_DENIED     32823
#define IDS_FILE_OPEN_SHARING_VIOLATION 32824
#define IDS_FILE_OPENED_NONDIRECT       32825
#define IDS_UNABLE_TO_CREATE_TEMPORARY_FILE 32826
#define IDS_UNABLE_TO_CREATE_NEW_FILE   32827
#define ID_INDICATOR_FILE_SIZE          32828
#define ID_INDICATOR_SELECTION_BEGIN    32829
#define ID_INDICATOR_SELECTION_LENGTH   32830
#define ID_INDICATOR_CURRENT_POS        32831
#define ID_INDICATOR_DUMMY              32832
#define ID_INDICATOR_SAMPLE_RATE        32833
#define ID_INDICATOR_SAMPLE_SIZE        32834
#define ID_INDICATOR_CHANNELS           32835
#define IDS_SOUND_CLIPPED               32836
#define IDS_SOUND_MAY_BE_CLIPPED        32837
#define IDS_M_UNABLE_TO_CREATE_UNDO     32838
#define IDS_STATISTICS_FORMAT           32839
#define IDS_REOPEN_IN_DIRECT_MODE       32840
#define IDS_RELOAD_COMPRESSED_FILE      32841
#define IDC_VIEW_AMPL_RULER_PERCENT     32900
#define ID_FILE_PROPERTIES              40000
#define ID_VIEW_ZOOMVERT_NORMAL         40001
#define ID_VIEW_ZOOMIN_HOR_FULL         40002
#define ID_EDIT_SELECTION               40003
#define ID_PROCESS_NORMALIZE            40004
#define ID_PROCESS_CHANGEVOLUME         40005
#define ID_PROCESS_DCOFFSET             40006
#define ID_PROCESS_RESAMPLE             40007
#define ID_PROCESS_MUTE                 40008
#define ID_PROCESS_INSERTSILENCE        40009
#define ID_FILE_REOPENFOREDITING        40010
#define ID_EDIT_REVERTALLCHANGES        40011
#define ID_EDIT_UNDO_ALL_CHANGES        40012
#define ID_STOP_ALL                     40013
#define IDC_PLAY_AND_STOP               -25522
#define ID_EDIT_MORE_UNDO_REDO          40015
#define ID_EDIT_CHANNELS_LOCK           40016
#define ID_SAMPLERATE_7200              40023
#define ID_SAMPLERATE_8000              40024
#define ID_SAMPLERATE_11025             40025
#define ID_SAMPLERATE_16000             40026
#define ID_SAMPLERATE_22050             40027
#define ID_SAMPLERATE_32000             40028
#define ID_SAMPLERATE_44100             40029
#define ID_SAMPLERATE_48K               40030
#define ID_SAMPLERATE_96K               40031
#define ID_SAMPLERATE_CUSTOM            40032
#define ID_CHANNELS_MONO                40033
#define ID_CHANNELS_STEREO              40034
#define ID_SAMPLE_16BIT                 40035
#define ID_SAMPLE_8BIT                  40036
#define ID_FFT_BANDS_64                 40037
#define ID_FFT_BANDS_128                40038
#define ID_FFT_BANDS_256                40039
#define ID_FFT_BANDS_512                40040
#define ID_FFT_BANDS_1024               40041
#define ID_FFT_BANDS_2048               40042
#define ID_FFT_BANDS_4096               40043
#define ID_FFT_BANDS_8192               40044
#define IDC_VIEW_STATUS_SAMPLES         40047
#define IDC_VIEW_STATUS_HHMMSS          40048
#define IDC_VIEW_STATUS_SECONDS         40049
#define ID_FILE_STATISTICS              40050
#define ID_PROCESS_INVERT               40051
#define ID_VIEW_OUTLINE                 40052
#define ID_VIEW_TIMERULER               40053
#define ID_VIEW_TIME_RULER              40055
#define ID_VIEW_VERTICAL_RULER          40056
#define ID_VIEW_RESCAN_PEAKS            40057
#define ID_PROCESS_SYNTHESIS_EXPRESSIONEVALUATION 40058
#define ID_PROCESS_SYNTHESIS_EXPRESSION_EVALUATION 40059
#define ID_VIEW_ZOOM_SELECTION          40060
#define ID_TOOLS_OPTIONS                40062
#define ID_TOOLS_INTERPOLATE            40063

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         40064
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
